name: RDP-Setup
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        run: |
          sudo apt-get update
          # تثبيت واجهة XFCE و XRDP
          sudo apt-get install -y xfce4 xfce4-goodies xrdp
          # إضافة إعدادات الواجهة للمستخدم runner
          echo xfce4-session > ~/.xsession
          # تعيين كلمة المرور
          echo "runner:123456" | sudo chpasswd
          # ضبط صلاحيات xrdp
          sudo adduser xrdp ssl-cert
          sudo systemctl restart xrdp
          
      - name: Install Cloudflare
        run: |
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
          chmod +x cloudflared
          
      - name: Start Tunnel
        run: |
          ./cloudflared tunnel --url rdp://localhost:3389 > tunnel.log 2>&1 &
          sleep 10
          echo "----------------------------------------"
          echo "رابط الوصول الخاص بك هو:"
          grep -o 'https://.*trycloudflare.com' tunnel.log
          echo "----------------------------------------"
          sleep 6h
