name: RDP

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start RDP
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          curl -sL https://gist.githubusercontent.com/cyb3rking/c03d7915598696700c25d81223280036/raw/rdp.sh | bash
