name: RDP-Setup
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install -y xrdp xfce4
          # تعيين كلمة مرور للمستخدم runner
          echo "runner:123456" | sudo chpasswd
          sudo systemctl enable xrdp
          sudo systemctl start xrdp
          
      - name: Install Cloudflare
        run: |
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
          chmod +x cloudflared
          
      - name: Start Tunnel
        run: |
          # تشغيل النفق وتوجيه السجلات لملف
          ./cloudflared tunnel --url rdp://localhost:3389 > tunnel.log 2>&1 &
          
          echo "جاري تشغيل النفق، يرجى الانتظار 20 ثانية..."
          sleep 20
          
          echo "----------------------------------------"
          echo "رابط الوصول الخاص بك هو:"
          grep -o 'https://.*trycloudflare.com' tunnel.log
          echo "----------------------------------------"
          
          sleep 6h
